export const staticLandingContent = {
  alternates: {
    ru: "https://adshortsai.com/",
    en: "https://adshortsai.com/en/",
    "x-default": "https://adshortsai.com/",
  },
  assets: {
    css: "styles.css?v=53",
    script: "script.js?v=6",
    logo: "logo.png?v=2",
    favicon: {
      png120: "favicon.png",
      png48: "favicon-48.png",
      png32: "favicon-32.png",
      png16: "favicon-16.png",
      svg: "favicon.svg",
      ico: "favicon.ico",
    },
    flags: {
      ru: "flags/ru.svg",
      en: "flags/us.svg",
    },
  },
  yandexVerification: ["98ced54b6a337450", "b95e4ede4fd42a24"],
  locales: {
    ru: {
      path: "index.html",
      lang: "ru",
      canonical: "https://adshortsai.com/",
      assetPrefix: "./",
      title: "AdShorts AI — Shorts/Reels/TikTok за 1 минуту",
      description: "AdShorts AI — автоматическое создание вертикальных видео за 1 минуту.",
      ogUrl: "https://adshortsai.com/",
      ogTitle: "AdShorts AI — видео за 1 минуту",
      ogDescription:
        "Вводите тему или оффер — получаете готовый вертикальный ролик: сценарий, субтитры, озвучка, музыка и фон.",
      twitterTitle: "AdShorts AI — видео за 1 минуту",
      twitterDescription: "ИИ-бот для генерации Shorts/Reels/TikTok с субтитрами и озвучкой.",
      softwareUrl: "https://adshortsai.com",
      softwareDescription:
        "AI-генератор для создания вертикальных видео Shorts, Reels и TikTok за 1 минуту. Автоматическая озвучка, субтитры, музыка и видеофон.",
      priceCurrency: "RUB",
      languageSwitch: {
        href: "./en/",
        title: "English",
        label: "RU",
        flagLocale: "ru",
        footerHref: "./en/",
        footerLabel: "English",
        footerHreflang: "en",
      },
      legalLinks: {
        offer: "./offer/",
        termsOfUse: "./terms-of-use/",
        terms: "./terms/",
        privacy: "./privacy/",
        dataDeletion: "./data-deletion.html",
      },
    },
    en: {
      path: "en/index.html",
      lang: "en",
      canonical: "https://adshortsai.com/en/",
      assetPrefix: "../",
      title: "AdShorts AI — Shorts/Reels/TikTok in 1 Minute",
      description: "AdShorts AI — automatic vertical video creation in 1 minute.",
      ogUrl: "https://adshortsai.com/en/",
      ogTitle: "AdShorts AI — Video in 1 Minute",
      ogDescription:
        "Enter a topic — get a ready vertical video: script, subtitles, voiceover, music, and background.",
      twitterTitle: "AdShorts AI — Video in 1 Minute",
      twitterDescription: "AI bot for generating Shorts/Reels/TikTok with subtitles and voiceover.",
      softwareUrl: "https://adshortsai.com/en/",
      softwareDescription:
        "AI generator for creating vertical Shorts, Reels, and TikTok videos in 1 minute. Auto voiceover, subtitles, music, and video background.",
      priceCurrency: "USD",
      languageSwitch: {
        href: "../",
        title: "Русский",
        label: "EN",
        flagLocale: "en",
        footerHref: "../",
        footerLabel: "Русский",
        footerHreflang: "ru",
      },
      legalLinks: {
        offer: "../offer/",
        termsOfUse: "./terms-of-use/",
        terms: "./terms/",
        privacy: "./privacy/",
        dataDeletion: "./data-deletion/",
      },
    },
  },
  messages: {
    navAria: { ru: "Основная навигация", en: "Main navigation" },
    navToggle: { ru: "Меню", en: "Menu" },
    navHome: { ru: "Главная", en: "Home" },
    navHow: { ru: "Как работает", en: "How it works" },
    navSamples: { ru: "Примеры", en: "Examples" },
    navPricing: { ru: "Тарифы", en: "Pricing" },
    navStudio: { ru: "Студия", en: "Studio" },
    navSignin: { ru: "Войти", en: "Sign in" },
    navFaq: { ru: "FAQ", en: "FAQ" },
    heroSuffix: { ru: "за 1 минуту. В один клик.", en: "in 1 Minute. In one click." },
    heroLead: {
      ru: "Введите тему — получите готовый вертикальный ролик с озвучкой, субтитрами, музыкой и видеофоном.",
      en: "Enter a topic — get a ready vertical video with voiceover, subtitles, music, and video background.",
    },
    heroCta: { ru: "Создать видео бесплатно", en: "Create Video for Free" },
    heroCtaNote: {
      ru: "Откроется студия — ролик можно собрать за минуту и сразу протестировать правки.",
      en: "Studio opens — build a video in a minute and instantly test edits.",
    },
    howTitle: { ru: "Как это работает", en: "How It Works" },
    optional: { ru: "Дополнительно", en: "Optional" },
    samplesTitle: { ru: "Примеры роликов", en: "Sample Videos" },
    soundToggle: { ru: "Включить звук", en: "Unmute video" },
    benefitsTitle: { ru: "Что внутри каждого ролика", en: "What's Inside Each Video" },
    pricingTitle: { ru: "Тарифы", en: "Pricing" },
    pricingIntro: {
      ru: null,
      en: "Pay with <strong>Telegram Stars ⭐</strong> — Telegram's built-in currency",
    },
    packsTitle: { ru: "Дополнительные пакеты", en: "Video Packs ⭐" },
    packsSubtitle: { ru: "Для активных пользователей Pro и Ultra", en: "For active Pro and Ultra users" },
    packsNote: { ru: "Докупите видео в любой момент. Баланс не сгорает.", en: "Buy more videos anytime. Balance never expires." },
    paymentTitle: { ru: null, en: "💫 How to Pay with Telegram Stars" },
    paymentNote: {
      ru: null,
      en: "💡 Don't have Stars? Buy them directly in Telegram: Settings → My Stars → Buy Stars",
    },
    guidesTitle: { ru: "Гайды по Shorts", en: "Shorts Guides" },
    guidesIntro: {
      ru: "Подборка материалов по темам: проблемы, удержание, сценарий, монтаж, рост и стратегия.",
      en: "Practical materials on the most common topics: problems, retention, scripts, editing, growth, and strategy.",
    },
    guidesAll: { ru: "Все материалы →", en: "All materials →" },
    faqTitle: { ru: "Частые вопросы", en: "Frequently Asked Questions" },
    finalCtaTitle: { ru: "Готовы создать первый ролик?", en: "Ready to Create Your First Video?" },
    finalCtaLead: { ru: null, en: "Open Studio and get a ready video in just a minute." },
    finalCtaButton: { ru: "Создать видео бесплатно", en: "Start Free" },
    contact: { ru: "Контакты:", en: "Contact:" },
    offer: { ru: "Публичная оферта", en: "Public Offer" },
    termsOfUse: { ru: "Условия использования", en: "Terms of Use" },
    terms: { ru: "Пользовательское соглашение", en: "User Agreement" },
    privacy: { ru: "Политика конфиденциальности", en: "Privacy Policy" },
    dataDeletion: { ru: "Удаление данных", en: "Data Deletion" },
  },
  heroFeatures: {
    ru: ["Оптимизирован под Shorts", "Всё делается автоматически", "Готово к публикации"],
    en: ["Optimized for Shorts", "Everything is done automatically", "Ready to publish"],
  },
  howSteps: [
    {
      number: "1",
      title: { ru: "Введите тему", en: "Enter a Topic" },
      text: { ru: "Напишите, о чём должен быть ролик.", en: "Describe what your video should be about." },
      type: "main",
    },
    {
      number: "2",
      title: { ru: "Получите видео", en: "Get Your Video" },
      text: {
        ru: "Готовый вертикальный ролик менее чем за минуту — с заголовком, описанием и хештегами, полностью готовый к публикации. Можно подключить YouTube-канал через Google OAuth и публиковать видео прямо из сервиса.",
        en: "A ready vertical video in less than a minute — with title, description, and hashtags, fully ready to publish. You can connect your YouTube channel via Google OAuth and publish directly from the Service.",
      },
      note: { ru: "Всё создаётся автоматически — в один клик.", en: "Everything is created automatically — in one click." },
      type: "main",
    },
    {
      title: { ru: "Настройте детали", en: "Customize Details" },
      text: {
        ru: "Выберите голос, музыку, текст, цвет субтитров, бренд, а также видеофон.",
        en: "Choose voice, music, subtitle text, color, brand, and video background.",
      },
      type: "optional",
    },
  ],
  samples: [
    {
      video: { ru: "1ru.mp4?v=2", en: "1en.mp4?v=2" },
      title: { ru: "Продажи услуг", en: "Service Sales" },
      text: { ru: "Хук → боль → решение → призыв", en: "Hook → Pain → Solution → CTA" },
    },
    {
      video: { ru: "2ru.mp4?v=2", en: "2en.mp4?v=2" },
      title: { ru: "Контент-канал", en: "Content Channel" },
      text: { ru: "Факты, подборки, цитаты", en: "Facts, lists, quotes" },
    },
    {
      video: { ru: "3ru.mp4?v=2", en: "3en.mp4?v=2" },
      title: { ru: "Маркетинг", en: "Marketing" },
      text: { ru: "A/B-тесты креативов", en: "A/B creative testing" },
    },
  ],
  benefits: [
    {
      title: { ru: "🎬 Сценарий", en: "🎬 Script" },
      text: {
        ru: "Цепляющий текст с сильным хуком под формат коротких видео.",
        en: "Engaging text with a strong hook optimized for short-form video.",
      },
    },
    {
      title: { ru: "📝 Субтитры", en: "📝 Subtitles" },
      text: {
        ru: "Стильные, читаемые, подсветка слов в ритме речи. Несколько вариантов оформления.",
        en: "Stylish, readable, word highlighting synced to speech. Multiple styles available.",
      },
    },
    {
      title: { ru: "🎙 Озвучка", en: "🎙 Voiceover" },
      text: { ru: "Качественные голоса на выбор — мужской или женский.", en: "High-quality voices to choose from — male or female." },
    },
    {
      title: { ru: "🎵 Музыка", en: "🎵 Music" },
      text: {
        ru: "Автоматический подбор под настроение или использование своего трека.",
        en: "Auto-selected to match the mood or upload your own track.",
      },
    },
    {
      title: { ru: "🎥 Видеофон", en: "🎥 Video Background" },
      text: {
        ru: "Автоматический подбор видеоряда по сценарию или использование своих видео и изображений.",
        en: "Auto-selected by AI or use your own videos and images.",
      },
    },
    {
      title: { ru: "🔄 Пересборка", en: "🔄 Regeneration" },
      text: { ru: "Хотите изменить результат? Меняйте любой элемент и генерируйте заново.", en: "Don't like it? Change any element and regenerate." },
    },
  ],
  plans: [
    {
      name: "Free",
      description: { ru: "Для знакомства с платформой", en: "Try the platform" },
      videos: { ru: "1 видео", en: "1 video" },
      price: { ru: "0 ₽", en: "0 ⭐" },
      perVideo: { ru: null, en: null },
      badge: { ru: null, en: null },
      hotBadge: false,
      features: { ru: ["С водяным знаком"], en: ["With watermark"] },
      neutralFeature: true,
      cta: { ru: "Начать бесплатно", en: "Start Free" },
      dataStart: { ru: "pricing_free", en: "pricing_free_en" },
      featured: false,
      bestValue: false,
    },
    {
      name: "Pro",
      description: { ru: "Для регулярного контента", en: "For regular content" },
      videos: { ru: "25 видео", en: "25 videos/month" },
      price: { ru: "1 490 ₽/мес", en: "1,200 ⭐" },
      usd: { ru: null, en: "(~$24)" },
      perVideo: { ru: "~60 ₽ за видео", en: "~$0.96/video" },
      badge: { ru: "Рекомендуем", en: "Recommended" },
      hotBadge: false,
      features: { ru: ["Без водяного знака"], en: ["No watermark"] },
      cta: { ru: "Перейти на Pro", en: "Upgrade to Pro" },
      dataStart: { ru: "pricing_pro", en: "pricing_pro_en" },
      featured: true,
      bestValue: false,
    },
    {
      name: "Ultra",
      description: { ru: "Максимум видео по лучшей цене", en: "Maximum videos, best price" },
      videos: { ru: "100 видео", en: "100 videos/month" },
      price: { ru: "4 990 ₽/мес", en: "3,500 ⭐" },
      usd: { ru: null, en: "(~$70)" },
      perVideo: { ru: "~50 ₽ за видео", en: "~$0.70/video" },
      badge: { ru: "🔥 Лучшая цена", en: "🔥 Best Value" },
      hotBadge: true,
      features: { ru: ["Без водяного знака", "Лучшая цена за видео"], en: ["No watermark", "Best price per video"] },
      cta: { ru: "Выбрать Ultra", en: "Choose Ultra" },
      dataStart: { ru: "pricing_ultra", en: "pricing_ultra_en" },
      featured: false,
      bestValue: true,
    },
  ],
  packs: [
    {
      name: "Pack 10",
      videos: { ru: "10 видео", en: "10 videos" },
      price: { ru: "690 ₽", en: "500 ⭐" },
      usd: { ru: null, en: "(~$10)" },
      perVideo: { ru: "~69 ₽/видео", en: "~$1.00/video" },
      badge: { ru: null, en: null },
    },
    {
      name: "Pack 50",
      videos: { ru: "50 видео", en: "50 videos" },
      price: { ru: "2 750 ₽", en: "2,000 ⭐" },
      usd: { ru: null, en: "(~$40)" },
      perVideo: { ru: "~55 ₽/видео", en: "~$0.80/video" },
      badge: { ru: null, en: null },
    },
    {
      name: "Pack 100",
      videos: { ru: "100 видео", en: "100 videos" },
      price: { ru: "4 990 ₽", en: "3,500 ⭐" },
      usd: { ru: null, en: "(~$70)" },
      perVideo: { ru: "~50 ₽/видео", en: "~$0.70/video" },
      badge: { ru: "Выгодно", en: "Best Deal" },
    },
  ],
  paymentSteps: {
    ru: [],
    en: [
      ["Open the bot", "click any button above to go to @AdShortsAIBot"],
      ["Choose a plan", "select Pro, Ultra, or a Pack in the bot menu"],
      ["Pay with Stars", "confirm payment using your Telegram Stars balance"],
      ["Done!", "your videos are credited instantly"],
    ],
  },
  guideTopics: [
    {
      href: "./shorts-guides/#problems",
      emoji: "🚨",
      title: { ru: "Проблемы и ошибки", en: "Problems & mistakes" },
      count: { ru: "18 гайдов", en: "18 guides" },
      text: { ru: "Диагностика проблем и быстрые действия для их решения", en: "Diagnostics and quick actions to fix issues." },
    },
    {
      href: "./shorts-guides/#retention",
      emoji: "📈",
      title: { ru: "Удержание и структура", en: "Retention & structure" },
      count: { ru: "13 гайдов", en: "13 guides" },
      text: {
        ru: "Первые секунды, темп, прогресс, повороты, «петля» и финальная точка",
        en: "The first seconds, pacing, progress, twists, loop, and a clear finish.",
      },
    },
    {
      href: "./shorts-guides/#texts",
      emoji: "✍️",
      title: { ru: "Сценарий и тексты", en: "Scripts & on-screen text" },
      count: { ru: "12 гайдов", en: "12 guides" },
      text: {
        ru: "Шаблоны сценариев, тексты на экране и «следующий шаг» без спама",
        en: "Script templates, on-screen copy, and a “next step” without spam.",
      },
    },
    {
      href: "./shorts-guides/#production",
      emoji: "🎬",
      title: { ru: "Монтаж и продакшен", en: "Editing & production" },
      count: { ru: "24 гайда", en: "24 guides" },
      text: { ru: "Техническая база и оформление: картинка, звук, субтитры, монтаж", en: "Video, sound, subtitles, and export settings — the technical foundation." },
    },
    {
      href: "./shorts-guides/#growth",
      emoji: "🚀",
      title: { ru: "Рост и рекомендации", en: "Growth & recommendations" },
      count: { ru: "9 гайдов", en: "9 guides" },
      text: { ru: "Метрики, тесты и регулярность — чтобы расти системно", en: "Metrics, testing, and consistency — to grow systematically." },
    },
    {
      href: "./shorts-guides/#strategy",
      emoji: "🎯",
      title: { ru: "Стратегия", en: "Strategy" },
      count: { ru: "16 гайдов", en: "16 guides" },
      text: {
        ru: "Ниша, идеи, контент‑план и серийность — основа для стабильного роста",
        en: "Niche, ideas, content planning, and series — for stable long-term growth.",
      },
    },
  ],
  faqs: [
    {
      question: { ru: "Нужно ли уметь монтировать?", en: "Do I need to know how to edit video?" },
      answer: { ru: "Нет. Видео генерируется автоматически — вы только задаёте тему.", en: "No. AI handles all the editing — you just enter a topic and parameters (optional)." },
      open: true,
    },
    {
      question: {
        ru: "Нужно ли описывать формат в описании для генерации видео?",
        en: "Do I need to describe the format in the description for video generation?",
      },
      answer: {
        ru: "AdShorts AI автоматически подбирает формат, длительность, стиль и озвучку под каждую идею. Если вы укажете инструкции вручную, результат может быть менее точным. Просто напишите идею — AI сделает всё остальное.",
        en: "AdShorts AI automatically selects the format, duration, style, and voiceover for each idea. If you specify instructions manually, the result may be less accurate. Just write the idea — AI will do the rest.",
      },
    },
    {
      question: { ru: "Можно ли использовать свои файлы?", en: "Can I use my own files?" },
      answer: { ru: "Да. Вы можете загрузить собственные видео/изображения и музыку.", en: "Yes. You can upload your own videos/images and music." },
    },
    {
      question: { ru: "Сколько занимает время?", en: "How long does it take?" },
      answer: { ru: "Обычно около 1 минуты на ролик (зависит от длины и загрузки).", en: "Usually about 1 minute per video (depends on length and server load)." },
    },
    {
      question: { ru: "Есть ли водяной знак?", en: "Is there a watermark?" },
      answer: {
        ru: "Да, водяной знак есть только в Free-тарифе. На платных — без водяного знака.",
        en: "Yes, watermark is only on Free tier. Paid plans have no watermark.",
      },
    },
    {
      question: { ru: "Можно ли использовать ролики в коммерческих целях?", en: "Can I use videos for commercial purposes?" },
      answer: {
        ru: "Да, если у вас есть права на загружаемые материалы. Для фонов используются сток-библиотеки и/или ваши файлы.",
        en: "Yes, if you have rights to uploaded materials. Backgrounds use stock libraries and/or your files.",
      },
    },
    {
      question: { ru: "Что если результат не понравился?", en: "What if I don't like the result?" },
      answer: {
        ru: "Вы можете изменить параметры (фон/музыку/озвучку/субтитры) и пересобрать ролик.",
        en: "You can change parameters (background/music/voiceover/subtitles) and regenerate the video.",
      },
    },
    {
      question: { ru: "Списываются ли генерации при редактировании?", en: "Are generations deducted when editing?" },
      answer: {
        ru: "Да. Каждое редактирование создаёт новое видео и списывает одну генерацию из вашего баланса.",
        en: "Yes. Each edit creates a new video and deducts one generation from your balance.",
      },
    },
    {
      question: {
        ru: "Какие разрешения запрашиваются при подключении YouTube?",
        en: "What permissions are requested when connecting YouTube?",
      },
      answerHtml: {
        ru: 'Только разрешения, необходимые для авторизации и публикации видео. Доступ можно отозвать в любой момент в настройках Google: <a href="https://myaccount.google.com/permissions" target="_blank" rel="noopener nofollow">myaccount.google.com/permissions</a>.',
        en: 'Only permissions required for authorization and video publishing are requested. You can revoke access at any time in Google account permissions: <a href="https://myaccount.google.com/permissions" target="_blank" rel="noopener nofollow">myaccount.google.com/permissions</a>.',
      },
    },
  ],
};
