export const STUDIO_SEGMENT_INFOGRAPHIC_FADE_SECONDS = 1;
export const STUDIO_SEGMENT_INFOGRAPHIC_HOLD_SECONDS = 1;
export const STUDIO_SEGMENT_INFOGRAPHIC_PART_REVEAL_SECONDS = 1.3;
export const STUDIO_SEGMENT_INFOGRAPHIC_LEGACY_PART_REVEAL_SECONDS = 0.65;
export const STUDIO_SEGMENT_INFOGRAPHIC_TIMING_SCALE = 2;
