export const WORKSPACE_SEGMENT_REFERENCE_FRAME_END_OFFSET_SECONDS = 0.25;
export const WORKSPACE_SEGMENT_REFERENCE_FRAME_SEEK_SECONDS = 0.25;
export const WORKSPACE_SEGMENT_REFERENCE_FRAME_LATEST_DECODABLE_OFFSET_SECONDS = 0.05;
export const WORKSPACE_SEGMENT_REFERENCE_FRAME_MAX_SIDE = 1280;
